---
- name: Set up benchmarker
  hosts: dima
  remote_user: yordan
  # become: yes
  # become_method: sudo


  tasks:
    
    - name: install dependencies
      become: yes
      apt:
        update-cache: yes
        pkg:
        - python3-pip
        - postgresql
        - postgresql-contrib
        - postgresql-plpython3-12
        - libpq-dev
        - git
        - make
        - gcc
        - mosh
        - tmux


    - name: send private key (dangerous)
      ansible.builtin.copy:
        src: ~/.ssh/id_ed25519
        dest: ~/.ssh/id_ed25519
        owner: "{{ansible_user}}"
        mode: '0400'

    - name: Create app dir if not exist
      become: yes
      ansible.builtin.file:
        path: /vagrant
        state: directory
        mode: '0777'

    - name: Clone from git
      # become: yes
      ansible.builtin.git:
        repo: git@github.com:yordangrigorov97/p2d2.git
        dest: /vagrant
        depth: 1
        accept_hostkey: yes

    - name: Install python requirements
      become: yes
      pip:
        requirements: /vagrant/requirements.txt
      
        # UNTESTED
    - name: Create postgres p2d2 user
      become: yes
      become_user: postgres
      postgresql_user:
        name: p2d2
        password: p2d2
        role_attr_flags: SUPERUSER

    # Now you have to manually generate data for the benchmarks and import them to postgresql
    # see deployment-scripts/1prepare_postgresql.sh
    #
    # - name: Create a new database with name "acme"
    #   community.postgresql.postgresql_db:
    #     name: acme
             

