---
- name: Set up benchmarker
  hosts: localhost
  # remote_user: yordan
  # become: yes
  # become_method: sudo


  tasks:
    
    - name: install dependencies
      become: yes
      apt:
        update-cache: yes
        pkg:
        - python3-pip
        - postgresql
        - postgresql-contrib
        - postgresql-plpython3-12
        - libpq-dev
        - git
        - make
        - gcc
        - mosh
        - tmux


    - name: send private key (dangerous)
      ansible.builtin.copy:
        src: ~/.ssh/id_ed25519
        dest: ~/.ssh/id_ed25519
        owner: "{{ansible_user}}"
        mode: '0400'

    - name: Create app dir if not exist
      become: yes
      ansible.builtin.file:
        path: /vagrant
        state: directory
        mode: '0777'

    - name: Clone/Pull from git
      # become: yes
      ansible.builtin.git:
        repo: git@github.com:yordangrigorov97/p2d2.git
        dest: /vagrant
        depth: 1
        accept_hostkey: yes

    - name: Install python requirements
      become: yes
      pip:
        requirements: /vagrant/requirements.txt
      
    # Requires :
    
    # [defaults]
    # allow_world_readable_tmpfiles = True
    # pipelining = True
    
    # in ~/.ansible.cfg
    - name: Create postgres root user
      become: yes
      become_user: postgres
      postgresql_user:
        name: root
        password: root
        role_attr_flags: SUPERUSER

    - name: Create postgres disable_nestloop_user user
      become: yes
      become_user: postgres
      postgresql_user:
        name: disable_nestloop_user
        password: disable_nestloop_user
        role_attr_flags: SUPERUSER

    - name: disable nestloop for the respective user
      become: yes
      become_user: postgres
      postgresql_query:
        # db: postgres
        query: ALTER ROLE disable_nestloop_user SET enable_nestloop=off

        #    - name: Create a new database for p2d2 user (ease interactivity)
        #      become: yes
        #      become_user: postgres
        #      postgresql_db:
        #        name: p2d2
        
    - name: Create a new database for root user (ease interactivity)
      become: yes
      become_user: postgres
      postgresql_db:
        name: root
    
    - name: Create a new database for disable_nestloop_user user (ease interactivity)
      become: yes
      become_user: postgres
      postgresql_db:
        name: disable_nestloop_user

      # increase postgresql max_connections to 1000

        # Now you have to:
        # 1. load the dumps to postgresql
        # 2. activate the udfs for all databases
    #
    # pg_restore [connection-option...] [option...] [filename]
             

